version: "3.9"
services:
  app:
    build: .
    container_name: logto
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:Pk6zBaJp2xsXA8TB@172.21.16.6:5432/user
      - ENDPOINT=https://auth.onsanhu.com
      - ADMIN_ENDPOINT=https://authadmin.onsanhu.com
      - TZ=Asia/Shanghai
